### ISSUE TITLE
Input folder name?

### ISSUE THREAD

**Issue by amouly** [maierj/fastlane-action#1]
Is there a way to `input` the folder where the Lane should be executed?

Asking because, on my Flutter project, Fastlane is setup on 2 folders like `/ios` and `/android`. Each of those have different Fastfiles.

I would like to select the input folder where the lane should be executed.

Thanks.

**Comment by maierj** [comment]
I created a new version of the action that includes an optional parameter called `subdirectory` where you can specify an optional path from the project root to the subdirectory where the fastlane folder is located. In your case the workflow steps should look like
```
uses: maierj/fastlane-action@0.9.3
      with:
        lane: <lane>
        subdirectory: 'ios'
```
and
```
uses: maierj/fastlane-action@0.9.3
      with:
        lane: <lane>
        subdirectory: 'android'
```
