### ISSUE TITLE
build fail after upgrade to v3 

### ISSUE THREAD

**Issue by riderx** [maierj/fastlane-action#105]
<img width="730" alt="CleanShot 2023-01-17 at 13 32 32@2x" src="https://user-images.githubusercontent.com/4084527/212817751-6c782675-2fb1-4289-b9e4-06fa953637a2.png">
old config who work

```yml
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: '2.7.2'
        - uses: maierj/fastlane-action@v2.3.0
          with:
            lane: closed_beta
```
update

```yml
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.0'
            bundler-cache: true
        - uses: maierj/fastlane-action@v3.0.0
          with:
            lane: closed_beta
```
