### ISSUE TITLE
how to cache pods ?

### ISSUE THREAD

**Issue by romk1n** [maierj/fastlane-action#107]
thank you for the great action, can you advise how we can cache pods as they take ages when we make build with fastlane to install ? many thanks.

**Comment by idlework** [comment]
Caching pods can be done with the `Cache` action

```yml
- name: Get Cocoapods cache directory
  uses: actions/cache@v3
    with:
      path: ios/Pods
      key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      restore-keys: ${{ runner.os }}-pods-
```
