### ISSUE TITLE
unknown ISA `XCLocalSwiftPackageReference Error when Xcode 15 

### ISSUE THREAD

**Issue by piggy-park** [maierj/fastlane-action#110]
Recently i've updated xcode version to 15.0
and i faced this error

<img width="1458" alt="스크린샷 2023-10-05 오후 1 12 10" src="https://github.com/maierj/fastlane-action/assets/111336385/8178c518-ae73-4eb4-b844-f81c0f845bda">

So i added update fastlane code, it worked
What i curious is this code is necessary?
Because it works without it
```
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
```
i've really confused because of this sentence from readme
`anyone using this action should set the bundler-cache parameter of the ruby/setup-ruby step to true (see [Example Usage](https://github.com/maierj/fastlane-action#example-usage)).`

### will fail
```
runs:
runs:
  using: "composite"
  steps:
    - name: bundle lock add platform
      shell: bash
      run: |
        bundle lock --add-platform x86_64-darwin-20
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - uses: maierj/fastlane-action@v3.0.0
      with:
        lane: 'flight'
```

### will success
```
    - name: bundle lock add platform
      shell: bash
      run: |
        bundle lock --add-platform x86_64-darwin-20
    - name: update fastlane
      shell: bash
      run: |
        bundle update fastlane
        bundle exec fastlane update_plugins
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - uses: maierj/fastlane-action@v3.0.0
      with:
        lane: 'flight'
        verbose: true
```

### will success
```
    - name: bundle lock add platform
      shell: bash
      run: |
        bundle lock --add-platform x86_64-darwin-20
    - name: update fastlane
      shell: bash
      run: |
        bundle update fastlane
        bundle exec fastlane update_plugins
    - uses: maierj/fastlane-action@v3.0.0
      with:
        lane: 'flight'
        verbose: true
```
