### ISSUE TITLE
Error: Unable to load contents of file list

### ISSUE THREAD

**Issue by tomruijgrok** [maierj/fastlane-action#111]
I am running into an issue where I can't archive my app. Fastlane works locally on my computer. When I use this action I get the following error: 
`error: Unable to load contents of file list: '/Target Support Files/Pods-learningtogether/Pods-learningtogether-frameworks-Release-input-files.xcfilelist' (in target 'learningtogether' from project 'learningtogether')`

My .yml file looks like this:

```
name: build-ios 
    on:  
      workflow_dispatch: # To trigger manual build
        release:
          types: [published] 
      jobs:
        build:
    defaults:
      run:
        working-directory: app
      runs-on: macos-latest
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{             
          secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
    steps:
       - uses: actions/checkout@v3
       - uses: ruby/setup-ruby@v1
         with:
            ruby-version: '3.0'
            bundler-cache: true
            working-directory: 'app/ios'
       - uses: maierj/fastlane-action@v3.0.0
         with:
            lane: 'beta'
            subdirectory: 'app/ios'
```

btw I am using React Native.
