### ISSUE TITLE
Specify path for bundle install

### ISSUE THREAD

**Issue by sasjo** [maierj/fastlane-action#19]
I'd like to cache installed gems to speed up my build. This would be easier if bundler is used with the `--path vendor/bundle` parameter. Without it, I'm not aware of a cross-platform location to cache.

This would also match the [Ruby cache example](https://github.com/actions/cache/blob/master/examples.md#ruby---gem).

```
      - name: Cache Ruby gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
```
