### ISSUE TITLE
Long execution

### ISSUE THREAD

**Issue by mig35** [maierj/fastlane-action#47]
Hi, thanks for the awesome plugin!

I have a question. I'm using fastlane to deploy my flutter project and it looks like fastlane is doing too much work in ubuntu comparing to mac-os.

If I run my code in ubuntu it takes about 6 minutes for my project, while on mac-os only 1.5 minute.

The yml file is here:
```
 - name: Cache Fastlane
        id: cache-fastlane
        uses: actions/cache@v1
        with:
          path: 'vendor/bundle'
          key: ${{ runner.os }}-fastlane
- uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'deploy_internal'
          subdirectory: 'android'
          bundle-install-path: 'vendor/bundle'
```

This is true because before my lane it is installing a lot of things for ubuntu:

```
Executing lane deploy_internal on Linux.
Moving to subdirectory android
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Successfully installed slack-notifier-2.3.2
Successfully installed atomos-0.1.3
Successfully installed CFPropertyList-3.0.2
Successfully installed claide-1.0.3
Successfully installed colored2-3.1.2
Successfully installed nanaimo-0.2.6
Successfully installed xcodeproj-1.16.0
Successfully installed rouge-2.0.7
Successfully installed xcpretty-0.3.0
Successfully installed terminal-notifier-2.0.0
Successfully installed unicode-display_width-1.7.0
Successfully installed terminal-table-1.8.0
Successfully installed plist-3.5.0
Successfully installed public_suffix-2.0.5
......
......
Done installing documentation for slack-notifier, atomos, CFPropertyList, claide, colored2, nanaimo, xcodeproj, rouge, xcpretty, terminal-notifier, unicode-display_width, terminal-table, plist, public_suffix, addressable, multipart-post, word_wrap, tty-screen, tty-cursor, tty-spinner, babosa, colored, highline, commander-fastlane, excon, unf_ext, unf, domain_name, http-cookie, faraday, faraday-cookie_jar, faraday_middleware, fastimage, gh_inspector, json, mini_magick, multi_xml, rubyzip, security, xcpretty-travis-formatter, dotenv, naturally, simctl, jwt, declarative-option, declarative, uber, representable, retriable, mini_mime, multi_json, signet, memoist, os, googleauth, httpclient, google-api-client, google-cloud-env, google-cloud-errors, google-cloud-core, digest-crc, google-cloud-storage, emoji_regex, jmespath, aws-partitions, aws-eventstream, aws-sigv4, aws-sdk-core, aws-sdk-kms, aws-sdk-s3, fastlane after 270 seconds
71 gems installed
```

Can you help how to solve this?

**Comment by maierj** [comment]
Have you tried to check the output value `cache-hit` of the cache action? It indicates, if there was a match for the cache key.
You could insert a step between the cache step and the fastlane step that just echos this value, e.g.
```
- name: Cache Fastlane
  id: cache-fastlane
  uses: actions/cache@v1
  with:
    path: 'vendor/bundle'
    key: ${{ runner.os }}-fastlane
- name: Debug cache
  run: echo "Cache-Hit: ${{ steps.cache-fastlane.outputs.cache-hit }}"
- uses: maierj/fastlane-action@v1.4.0
  with:
    lane: 'deploy_internal'
    subdirectory: 'android'
    bundle-install-path: 'vendor/bundle'
```
