### ISSUE TITLE
SDK Not Found for React Native Project

### ISSUE THREAD

**Issue by pacarvalho** [maierj/fastlane-action#50]
For some reason, the following error occurs when I attempt to run my Action. Does this Action have any peer dependencies? 

```
| FAILURE: Build failed with an exception.
| 
| * Where:
| Build file '/github/workspace/node_modules/react-native-screens/android/build.gradle' line: 90
| 
| * What went wrong:
| A problem occurred configuring project ':react-native-screens'.
| > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/github/workspace/android/local.properties'.
```

```yaml
name: Deploy Android

on:
  push:
    branches:
      - master

jobs:
  deploy-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Create Upload Key
        run: echo ${{ secrets.UPLOAD_KEY }} | base64 -d >> upload-key.keystore
        working-directory: ./android

      - name: Install Packages
        run: yarn

      - name: Compile and Upload
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: "deploy_internal"
          subdirectory: "android"
          # options: '{ "MYAPP_UPLOAD_STORE_FILE": "./upload-key.keystore", "MYAPP_UPLOAD_STORE_PASSWORD": ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}, "MYAPP_UPLOAD_KEY_PASSWORD": ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}, "RNGP_ANDROID_API_KEY": ${{ secrets.RNGP_ANDROID_API_KEY }} }'
        env:
          MYAPP_UPLOAD_STORE_FILE: ./upload-key.keystore
          MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}
          RNGP_ANDROID_API_KEY: ${{ secrets.RNGP_ANDROID_API_KEY }}
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          ANDROID_SDK_ROOT: /home/admin/Android/Sdk
```

NOTE: Not sure if I am required to use the `options` flag or if it also works to use envs directly.
