### ISSUE TITLE
Subdirectory does not exist

### ISSUE THREAD

**Issue by airowe** [maierj/fastlane-action#51]
Trying to get this action (admittedly, my first) working with a React Native project. 

I have an ios subdirectory at the root of my project where the workflow is defined in `.github/workflows` that contains the `fastlane` directory.

Here's my yml file defining the job:

```
name: Fastlane to Testflight
# Trigger the workflow on push or pull request,
# but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Fastlane
    runs-on: macos-10.15
    env:
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
    steps:
      - name: Fastlane Action
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'beta'
          subdirectory: 'ios'
          options: '{ "option1": "--verbose" }'
          bundle-install-path: 'vendor/bundle'
```

However, I continue to get the following error: 

> Error: Specified subdirectory ios does not exist.

Do I have something configured incorrectly?
