### ISSUE TITLE
Caching Ruby dependencies doesn't seem to work

### ISSUE THREAD

**Issue by fjcaetano** [maierj/fastlane-action#63]
Hi there, let me start by thanking for this GH action. It greatly simplifies the workflow and keeps the YAML configuration much cleaner.

I'm trying to cache the Ruby dependencies installed by Bundler by using a step with `actions/cache`, however when the Fastlane step starts, it's always installing all the required dependencies.

The workflow is configured as:
```yaml
      - name: Run 'test' lane
        uses: maierj/fastlane-action@v2.0.0
        with:
          lane: test
          bundle-install-path: './vendor/bundle'
        env:
          FASTLANE_HIDE_CHANGELOG: true

      - name: Cache ruby dependencies
        uses: actions/cache@v2
        with:
          path: './vendor/bundle'
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
```

This is the beginning of the output log when the Fastlane step starts executing. I've trimmed it for brevity:
```
Run maierj/fastlane-action@v2.0.0
Executing lane test on macOS.
Fetching gem metadata from https://rubygems.org/........
Fetching rake 13.0.3
Installing rake 13.0.3
Fetching CFPropertyList 3.0.3
Installing CFPropertyList 3.0.3
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching addressable 2.7.0
Installing addressable 2.7.0
Fetching atomos 0.1.3
Installing atomos 0.1.3
Fetching aws-eventstream 1.1.0
Installing aws-eventstream 1.1.0
Fetching aws-partitions 1.415.0
Installing aws-partitions 1.415.0
...
```
