### ISSUE TITLE
Support for Environment Variables

### ISSUE THREAD

**Issue by AppleEducate** [maierj/fastlane-action#9]
When starting with Fastlane match, I am unable to pass my MATCH_PASSWORD 

I was able to get the Github secrets repo working by specifying the ssh keys first.

Here is my workflow so far:

```
name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'dev'
    - run: flutter pub get
    - run: flutter config --enable-web
    - run: flutter build web
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: web-build
        path: build/web
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'dev'
    - run: flutter pub get
    - run:  mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set Fastlane Env	
      run: echo Adding Tokens!	
      env:	
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}	
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - uses: maierj/fastlane-action@v0.9.5
      with:
        lane: 'beta'
        subdirectory: 'ios'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - name: Upload iPA
      uses: actions/upload-artifact@master
      with:
        name: web-build
        path: build/web
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'dev'
    - run: flutter pub get
    - run: flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: build/app/outputs/apk/release
  deploy_web:
    name: Deploy Web to Firebase Hosting
    needs: build_web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web-build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --public web-build
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: default
```

Here is the public repo if you are curious:

https://github.com/AppleEducate/flutter_piano

I am using this with Flutter and have Fastlane just on iOS at the moment.

Is there something i should be doing differently? I like how firebase can take the token from the `env`
