### ISSUE TITLE
bundler-cache is required? 

### ISSUE THREAD

**Issue by liangwangcm** [maierj/fastlane-action#90]
While I use `maierj/fastlane-action@v2.2.1`,  ruby `bundle-cache` is still recommended?

```
- uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.2"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```
