### ISSUE TITLE
Output values

### ISSUE THREAD

**Issue by sregg** [maierj/fastlane-action#96]
How do you output returned values from a fastlane action like [get_version_number](http://docs.fastlane.tools/actions/get_version_number/) ?

**Comment by sregg** [comment]
I managed to get it work using env vars.

In my `Fastfile`:

```
  desc "Increment build number"
  lane :increment_build do
    build_number = increment_build_number(
      skip_info_plist: true
    )
    sh("echo NEW_BUILD_NUMBER=#{build_number} >> $GITHUB_ENV")
  end
```

And in my GH action:

```
      - name: Increment build number
        uses: maierj/fastlane-action@v2.2.1
        with:
          lane: increment_build
          subdirectory: ios

      - name: Commit build number changes
        run: |
          echo "Build number incremented to $NEW_BUILD_NUMBER"
          git commit -am "Increment build number to $NEW_BUILD_NUMBER" --no-verify
          git push
```
